# Generated by Django 4.2.1 on 2024-01-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coursebookapp", "0009_remove_purchasedcourse_purchase_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasedcourse",
            name="course_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
